library(sf)
library(dplyr)
#library(mapview)

# Select FDA, input, and output files
fda_name <- "09EA" # "09EA", "10AB"
yg_dir <- "C:/Users/PIVER37/Documents/gisdata/YT/"
canada_gpkg <- "C:/Users/PIVER37/Documents/gisdata/123/canada.gpkg"
yg_gpkg <- "C:/Users/PIVER37/Documents/gisdata/123/yg_disturbances.gpkg"
fda_gpkg <- paste0("C:/Users/PIVER37/Documents/github/dc-mapping/data/fda_",tolower(fda_name),".gpkg")

# View available layers in Canada.gpkg
st_layers(canada_gpkg)

# Select one FDA
x <- st_read(canada_gpkg, 'NHN_Index') %>%
    filter(FDA==fda_name)
fda <- st_transform(x, crs=3578)

# Check that we have the correct FDA
#mapview(fda)

# Write to geopackage file
st_write(fda, fda_gpkg, "FDA", delete_layer=T, delete_dsn=T)

# Extract and clip IFL 2000 and 2020
ifl2000 <- st_read(canada_gpkg, "GIFL_2000") %>%
    st_intersection(x) %>%
    st_transform(crs=3578)
st_write(ifl2000, fda_gpkg, "IFL_2000", delete_layer=T)

ifl2020 <- st_read(canada_gpkg, "GIFL_2020") %>%
    st_intersection(x) %>%
    st_transform(crs=3578)
st_write(ifl2020, fda_gpkg, "IFL_2020", delete_layer=T)

# YG surface disturbance
areal <- st_read(yg_gpkg, "Areal_Features") %>%
    st_intersection(fda)
st_write(areal, fda_gpkg, "Areal_Features", delete_layer=T)

linear <- st_read(yg_gpkg, "Linear_Features") %>%
    st_intersection(fda)
st_write(linear, fda_gpkg, "Linear_Features", delete_layer=T)

point <- st_read(yg_gpkg, "Point_Features") %>%
    st_intersection(fda)
st_write(point, fda_gpkg, "Point_Features", delete_layer=T)

# Fires
fires <- st_read(paste0(yg_dir,'Emergency_Management/Fire_History.gdb'), 'Fire_History') %>%
    st_cast("MULTIPOLYGON") %>%
    st_intersection(fda)
st_write(fires, fda_gpkg, "Fire_History", delete_layer=T)

# Claims
quartz <- st_read(paste0(yg_dir,'Mining/Quartz_Claims_50k.gdb'), 'Quartz_Claims_50k') %>%
    st_cast("MULTIPOLYGON") %>%
    st_intersection(fda)
st_write(quartz, fda_gpkg, "Quartz_Claims", delete_layer=T)

# HydroBasins
